
USE [master]
GO

/****** Object:  Database [Baza_leki]    Script Date: 25.04.2016 19:53:54 ******/
CREATE DATABASE [Baza_leki]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Baza_leki', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Baza_leki.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Baza_leki_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Baza_leki_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Baza_leki] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Baza_leki].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Baza_leki] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Baza_leki] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Baza_leki] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Baza_leki] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Baza_leki] SET ARITHABORT OFF
GO

ALTER DATABASE [Baza_leki] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Baza_leki] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Baza_leki] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Baza_leki] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Baza_leki] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [Baza_leki] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Baza_leki] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Baza_leki] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Baza_leki] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Baza_leki] SET  DISABLE_BROKER
GO

ALTER DATABASE [Baza_leki] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Baza_leki] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Baza_leki] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Baza_leki] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Baza_leki] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Baza_leki] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Baza_leki] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Baza_leki] SET RECOVERY SIMPLE
GO

ALTER DATABASE [Baza_leki] SET  MULTI_USER
GO

ALTER DATABASE [Baza_leki] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [Baza_leki] SET DB_CHAINING OFF
GO

ALTER DATABASE [Baza_leki] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Baza_leki] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [Baza_leki] SET DELAYED_DURABILITY = DISABLED
GO

USE [Baza_leki]
GO

/****** Object:  Table [dbo].[Medicines_Table]    Script Date: 25.04.2016 19:53:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[Users_Table]    Script Date: 25.04.2016 19:53:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [Baza_leki] SET  READ_WRITE
GO

USE [master]
GO

/****** Object:  Database [Baza_leki]    Script Date: 13.05.2016 18:27:31 ******/
CREATE DATABASE [Baza_leki]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Baza_leki', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Baza_leki.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Baza_leki_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Baza_leki_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Baza_leki] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Baza_leki].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Baza_leki] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [Baza_leki] SET ANSI_NULLS OFF
GO

ALTER DATABASE [Baza_leki] SET ANSI_PADDING OFF
GO

ALTER DATABASE [Baza_leki] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [Baza_leki] SET ARITHABORT OFF
GO

ALTER DATABASE [Baza_leki] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [Baza_leki] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [Baza_leki] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [Baza_leki] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [Baza_leki] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [Baza_leki] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [Baza_leki] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [Baza_leki] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [Baza_leki] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [Baza_leki] SET  DISABLE_BROKER
GO

ALTER DATABASE [Baza_leki] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [Baza_leki] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [Baza_leki] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [Baza_leki] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [Baza_leki] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [Baza_leki] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [Baza_leki] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [Baza_leki] SET RECOVERY SIMPLE
GO

ALTER DATABASE [Baza_leki] SET  MULTI_USER
GO

ALTER DATABASE [Baza_leki] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [Baza_leki] SET DB_CHAINING OFF
GO

ALTER DATABASE [Baza_leki] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [Baza_leki] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [Baza_leki] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [Baza_leki] SET  READ_WRITE
GO
