//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines_Table
    {
        public int ID_leku { get; set; }
        public Nullable<int> ID { get; set; }
        public string Medicine_Name { get; set; }
        public string Dose { get; set; }
        public string Additional_Information { get; set; }
        public Nullable<System.DateTime> Beginning_Date { get; set; }
        public Nullable<System.DateTime> The_End_Date { get; set; }
        public Nullable<byte> Tolerance_Hour { get; set; }
        public Nullable<System.DateTimeOffset> Iteration { get; set; }
    
        public virtual Users_Table Users_Table { get; set; }
    }
}
